### ISSUE TITLE
代码高亮主题环境设置

### ISSUE THREAD

**Issue by XiangyunHuang** [XiangyunHuang/notesdown#26]
```r
knitr::knit_theme$set("print")
highlight_bw: yes
```

<img width="580" alt="default" src="https://user-images.githubusercontent.com/12031874/41273067-7fbbc2be-6e4a-11e8-9acb-fb758dc2deb8.PNG">

**Comment by XiangyunHuang** [comment]
直接用

```
set.seed(2018)
## 单位区域上随机采样
N <- 1600 # 样本量
d1 <- rnorm(N, 0, 1)
d2 <- rnorm(N, 0, 1)
dist <- dist(cbind(d1, d2)) # 计算采样点之间的欧氏距离
m <- sigma.sq * exp(-as.matrix(dist) / phi) # 多元高斯分布的协方差矩阵
S <- mvrnorm(1, rep(0, N), m) # 产生服从多元高斯分布的随机数
## 在规则网格的格点上采样
d <- expand.grid(
  d1 = seq(-0.2, 1.2, l = 7),
  d2 = seq(-0.2, 1.2, l = 7)
)
dist <- dist(d)
m <- sigma.sq * exp(-as.matrix(dist) / phi)
S <- mvrnorm(1, rep(0, N), m)
```

直接用 ```  而不标志任何语言

**Comment by XiangyunHuang** [comment]
正确的姿势是

```yaml
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
    before_body: before_body.tex
    after_body: after_body.tex     
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: no
  pandoc_args: "--top-level-division=chapter"
  toc_depth: 3
  toc_bib: yes
  toc_unnumbered: no
  toc_appendix: yes
#  highlight_bw: no
  highlight: NULL
  template: default.latex
```

注意到没 `highlight: NULL`
